name: incremental_dom_bindings
description: Dart bindings for the Incremental DOM library. Incremental DOM is a library for expressing and applying updates to DOM trees incrementally.
version: 3.0.0
homepage: https://www.github.com/blimster/incremental_dom_bindings

environment:
  sdk: ^3.4.0

dependencies:
  web: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
